#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [ -t 1 ]; then
  exec < /dev/tty
fi

yarn test
yarn lint-staged

yarn add is-ci

if ! [ is-ci ]; then
  echo 'Do you want to version this update?'
  PS3='Answer: '
  options=("yes" "no")
  select opt in "${options[@]}"
  do
      case $opt in
          "yes")
              npx changeset
              git add .changeset/*
              exit 0
              ;;
          "no")
              exit 0
              ;;
          *) echo "invalid option $REPLY";;
      esac
  done
fi

exit 0

